AllCops:
  NewCops: enable
  Exclude:
    - "config/emacs/elpa/**/*"

Metrics:
  Enabled: false

Style/EnvHome:
  Enabled: false

Style/ExpandPathArguments:
  Exclude:
    - "cookbooks/**/*"

Style/FetchEnvVar:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - "cookbooks/**/*"
    - "lib/**/*"
    - "recipes/**/*"

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false
