AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Exclude:
    - "lib/**/*"
    - "cookbooks/**/*"

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false
