# see: https://github.com/Peltoche/lsd#config-file-content

# == Blocks ==
# This specifies the columns and their order when using the long and the tree
# layout.
# Possible values: permission, user, group, context, size, date, name, inode, links, git
blocks:
  - permission
  - user
  - group
  - size
  - date
  - git
  - name

date: +%F %T
